### ISSUE TITLE
Login pagina stopped working in dev branch

### ISSUE THREAD

**Issue by Job79** [maurictg/Overstag#9]
The login pagina stopped working in the dev branch.
![2020-06-16-205351_1920x1080_scrot](https://user-images.githubusercontent.com/38859657/84815816-e0c38a80-b013-11ea-8681-4c69e7b2d354.png)

**Comment by Job79** [comment]
Probably not working because of missing files, maybe add a build script to the repository?

**Comment by maurictg** [comment]
For some reason this happens only on Linux. This happens because the filename Overstag.min.js is not lowercase. This is fixed on the branch "vue" which will be merged with dev soon

**Comment by maurictg** [comment]
Please check it out, it must be solved in the dev branch right now.
